signalfx/splunk-otel-js

.eslintrc.js
index.js
instrument.js
src/index.ts
src/instrument.ts
src/instrumentations/index.ts
src/instrumentations/loader.ts
src/jaeger.ts
src/jaeger_patch.d.ts
src/options.ts
src/resource.ts
src/tracing.ts
src/version.ts
test/exporter.test.ts
test/instrument.test.ts
test/instrumentations.test.ts
test/options.test.ts
test/propagation.test.ts
test/resource.test.ts
test/tracing.test.ts

Enable eslint rule to ensure copyright headers are included in every source file

---

README.md
examples/express/package.json
src/options.ts
test/tracing.test.ts

No backward compability was added. This'll be a breaking change.

Replaced SPLUNK_TRACE_EXPORTER_URL with OTEL_EXPORTER_JAEGER_ENDPOINT

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/instrumentations/index.ts
src/instrumentations/loader.ts
test/instrumentations.test.ts

- Listed instrumentations as (optional) peer dependencies. This makes
require()'ing instrumentations safer despite @splunk/otel not listing
them as dependencies. Marking them optional ensures npm7 will not
automatically install these packages. Note that this will still result
in warnings for users on npm <7.
- Added suport for the following instrumentations out of the box:
- @opentelemetry/instrumentation-express
- @opentelemetry/instrumentation-ioredis
- @opentelemetry/instrumentation-mongodb
- @opentelemetry/instrumentation-mysql
- @opentelemetry/instrumentation-net
- @opentelemetry/instrumentation-pg
- @opentelemetry/instrumentation-hapi
- Removed support for the following instrumentations:
- @opentelemetry/hapi-instrumentation

More and better instrumentations

---

CHANGELOG.md
src/tracing.ts

Async hooks context manager needs to be activated by calling `.enable()`
before it can be used as a context manager. This is important for older
versions of node that don't use support local storage context manager.
We need to release this as a hot fix. Will follow up with a test case to catch any regressions in future.
fixes #50

Fix context manager for older node versions

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/instrumentations/http.ts
src/options.ts
src/tracing.ts
test/instrumentations.test.ts
test/options.test.ts
test/servertiming.test.ts

Enable injection of `Server-Timing` response headers. This also works if an user provides their own `HttpInstrumentation` with an existing response hook, so no additional code changes are needed for them except enabling the feature.
Tested manually with express and koa.

feat: add server timing header injection

---

package-lock.json
package.json
src/instrumentations/index.ts
test/instrumentations.test.ts

- opentelemetry-instrumentation-aws-sdk
- opentelemetry-instrumentation-kafkajs
- opentelemetry-instrumentation-sequelize
- opentelemetry-instrumentation-typeorm
- opentelemetry-instrumentation-mongoose

Added out of box support for more instrumentations:

---

CHANGELOG.md
package.json
src/version.ts

* Add support for injecting trace context into logs.
* Rename `SPLUNK_CONTEXT_SERVER_TIMING_ENABLED`
* Upgrade to OpenTelemetry SDK 0.22.0, API 1.0.0.

Release v0.9.0

---

.gitlab-ci.yml

npm publish was assuming `dist/splunk-otel-{version}.tgz` was a git repo
and tried to check it out when publishing which obviously failed.
Change it to a relative path tells npm to look for the file on disk
rather than github.

Fix npm publish command

---

CHANGELOG.md
README.md
src/options.ts
src/tracing.ts
test/loginjection.test.ts
test/options.test.ts
test/tracing.test.ts

Use OTel's `OTEL_SERVICE_NAME` instead of `SPLUNK_SERVICE_NAME`
Correcting this unnecessary divergence from the standard.
Also, needed for smoother migration process (#168)

chore: deprecate SPLUNK_SERVICE_NAME

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Rename `SPLUNK_SERVICE_NAME` to `OTEL_SERVICE_NAME`          
([#170](https://github.com/signalfx/splunk-otel-js/pull/170))
- Upgrade to OpenTelemetry SDK 0.23.0                          
([#173](https://github.com/signalfx/splunk-otel-js/pull/173))

Release v0.10.0

---

test/options.test.ts
test/resource.test.ts
test/servertiming.test.ts
test/tracing.test.ts
test/utils.ts

Implemented an utility to clear relevant environment variables before running the tests.
Current ones are fortunately well-implemented and didn't have any errors regarding that, but
I stumbled upon fragile tests adding new in another PR.

test: protect from environment leaking between tests

---

test/propagation.test.ts

One of the propagation tests would just time out if any of the assertions would fail.

test: catch errors from propagation test

---

package-lock.json
package.json
src/resource.ts

Gets rid of https://github.com/signalfx/splunk-otel-js/pull/283

chore: upgrade to TypeScript 4.4.3

---

test/options.test.ts

Fixes it for OTel JS 0.25.0, however in 0.26.0 this will be renamed to `W3CBaggagePropagator`.

test: fix import for HttpBaggagePropagator

---

.github/dependabot.yml

Else every day our PR list and git history is spammed with minor updates :cry: 
Also removed the ignored security params which are configured via GitHub and not via yaml.
GitHub's dependabot does not seem to have `allowed_updates` field any more, but has `allow` which however does not control security updates:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#allow

chore: update dependabot to run weekly

---

.github/dependabot.yml

Was meant to be removed with https://github.com/signalfx/splunk-otel-js/pull/322, but forgot to push changes :facepalm: 
The error can now even be seen in the main branch:
`The property '#/updates/0/' contains additional properties ["allowed_updates"] outside of the schema when none are allowed`

chore: fix unused dependabot parameters

---

README.md
docs/correlate-logs-traces.md
src/options.ts

Currently, we do not support setting `OTEL_TRACES_EXPORTER` to `''` to enforce the default. We need it to support clearing the env in env files for example.

fix: use default exporter when the env var is set to empty string

---

docs/advanced-config.md
src/instrumentations/http.ts
src/options.ts
test/options.test.ts
test/uri_parameter_capture.test.ts

Add the option to capture URL parameters from HTTP requests. Capturing can be done either by supplying a list of keys to capture (case-sensitive) or a custom function which gets invoked with the current span and query parameters.
Parameters are set as `http.request.param.${key}` span attribute.

feat: add the option to capture URL parameters

---

scripts/release-github.js

`release-github.js` had "jtmalinowski" hardcoded as the user/org.

chore: hardcode `signalfx` as the namespace for github release

---

change/@splunk-otel-14b0a128-e4ef-40f4-b5a3-e5f145bea2ff.json
change/@splunk-otel-43ecdcc3-f6b8-4c63-8b96-3b554cd79ae2.json
docs/advanced-config.md
src/options.ts
test/options.test.ts

- feat: set the defaults on limits
- feat: warn about missing service.name and no instrumentations
Addresses some of the concerns from GDI spec review.

feat: set the GDI-spec compliant defs and warn about missing service.name

---

docs/http-instrumentation.md

The example code was too wide :space_invader:

doc: fix whitespace in http instrumentation

---

docs/advanced-config.md
package-lock.json
src/metrics/index.ts
src/options.ts
test/metrics.test.ts

- Remove `host` dimension as it should come from collector
- Add `service` dimension with the same logic as is done for `startTracing`

Add service dimension to metrics

---

docs/troubleshooting.md

This PR adds a troubleshooting section on Webpack and the externals workaround.

Add Webpack workaround to Troubleshooting docs

---

README.md

Add the missing instrumentations that are loaded automatically in https://github.com/signalfx/splunk-otel-js/blob/main/src/instrumentations/index.ts

doc: update instrumentations list

---

src/native_ext/profiling.cpp
src/profiling/index.ts
src/profiling/profiling_contextmanager.ts

* Reduced preallocated bin count due to the lower collection threshold. Slight memory usage reduction.
* Unrelated: check for allocation failure, remove use of constexpr.

profiler: set default collection interval to 30s

---

change/@splunk-otel-c79d7401-d939-4997-b613-c4d48d65fdbe.json
docs/advanced-config.md
src/instrument.ts
src/metrics/index.ts
test/metrics.test.ts

Remove the completely unnecessary `enabled` flag from `startMetrics`. `startMetrics` should just start it, for CLI loads the env var is read at `instrument.ts` instead.

fix: remove enabled flag from startMetrics

---

package-lock.json
package.json

Not directly used in our code. OTel Jaeger exporter still brings in the package however.

chore: remove jaeger-client

---

CHANGELOG.json
CHANGELOG.md
change/@splunk-otel-c79d7401-d939-4997-b613-c4d48d65fdbe.json
examples/basic/package.json
examples/express/package.json
examples/log-injection/package.json
examples/logs/package.json
examples/mixed/package.json
package-lock.json
package.json
src/version.ts

- refactor: remove enabled flag from startMetrics options [#429](https://github.com/signalfx/splunk-otel-js/pull/429)
- chore: [update minimist to 1.2.6](https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795) [#435](https://github.com/signalfx/splunk-otel-js/pull/435)
- chore: remove unnecessary dependency on jaeger-client [#445](https://github.com/signalfx/splunk-otel-js/pull/445)
- plus various dependabot package updates

chore: release v0.18.0

---

.github/workflows/ci.yml
.gitlab-ci.yml

Tags with name matching `prerelease-v[0-9]+\.[0-9]+\.[0-9]+(?:-.+)?$`, e.g. `prerelease-v0.21.0` can be used to publish to npm. GitHub releases are skipped to avoid polluting releases list with experimental releases.

chore: allow gitlab prereleases

---

test/instrumentations.test.ts

if `loader silently fails when package is not installed` test fails, it brings down others and creates confusing output. Make sure the stub is removed even if the test fails.

test: do not leak the sinon stub to other tests on failure

---

change/@splunk-otel-7380d88c-bd30-4b35-aa18-8cc7a6b9192e.json
src/detectors/DistroDetector.ts
src/resource.ts
test/options.test.ts

Adds `splunk.distro.version` resource attribute.

feat: add `splunk.distro.version` resource attribute

---

MIGRATING.md
change/@splunk-otel-f3b2f067-abed-4f03-9116-9db66c560941.json
package.json

Drop official support for `node@8` and `node@10`. Will leave the builds and testing for now as an indicator to when we are actually starting to break for those versions.

chore: remove support for older Node versions than LTS 12

---

README.md
change/@splunk-otel-b97ec2d2-5809-4cf8-89ee-0dde69350680.json
package.json
src/instrumentations/index.ts
test/instrumentations.test.ts

All other supported instrumentation versions depend on `@opentelemetry/instrumentation@0.27` or later. Aspectos AWS SDK instrumentation is depending on the older one and will never be updated because it's now moved over to OTel repo.
Different versions of `@opentelemetry/instrumentation` certainly break for stricter TS compilations and possibly cause issues in meta-packages, autoloaders or when packages are hoisted in monorepos.

fix: remove Aspecto's aws sdk instrumentation

---

CHANGELOG.json
CHANGELOG.md
README.md
change/@splunk-otel-42417487-cc55-467d-b741-9e94bb35bb9e.json
change/@splunk-otel-664a01b7-34ea-48bf-a30a-cf272a2d0402.json
change/@splunk-otel-720ca615-45a6-44a5-832e-ac1622535e24.json
change/@splunk-otel-7380d88c-bd30-4b35-aa18-8cc7a6b9192e.json
change/@splunk-otel-78671426-1296-47f4-bc37-ca6089c4d441.json
change/@splunk-otel-835859df-2920-4280-93ed-07aba289641d.json
change/@splunk-otel-acb2dc51-51a5-46ca-98e5-6800ba8497b6.json
change/@splunk-otel-b10e9b93-358f-4659-a0ae-6238abb6116c.json
change/@splunk-otel-b97ec2d2-5809-4cf8-89ee-0dde69350680.json
change/@splunk-otel-b99ffa99-f72c-4906-bfe8-2ab9119626ae.json
change/@splunk-otel-c1f5d9c4-8f57-4d27-a88c-bebce002f03a.json
change/@splunk-otel-d8cc588a-a981-4d72-90a6-4fd68f98cb00.json
change/@splunk-otel-f3b2f067-abed-4f03-9116-9db66c560941.json
change/@splunk-otel-f9a678c1-47b2-43b4-a3cd-52470d587002.json
examples/basic/package.json
examples/express/package.json
examples/log-injection/package.json
examples/logs/package.json
examples/mixed/package.json
package.json
src/metrics/index.ts
src/profiling/index.ts
src/tracing/index.ts
src/version.ts

chore: release v1.0.0

---

.github/workflows/ci.yml

Move prebuilds and tests to at least Node.js 12.13

chore: remove builds and tests on outdated Node.js versions

---

src/profiling/index.ts
src/profiling/types.ts
test/profiling/extension.test.ts
test/profiling/profiling.test.ts

Verifies the types received from native extension and that profiling data is exported.
The logs exporter is not tested as we're about to throw it away anyway in favor of pprof.

test: add a few smoke tests for profiling

---

change/@splunk-otel-345cf72a-5e0b-4e99-9034-dd82ede484b4.json
src/native_ext/profiling.cpp
test/profiling/extension.test.ts

For pprof it's useful to start with informatted stacktraces. Implemented a way to export that format instead of parsing already formatted stacktrace strings.
This introduces a lot of code duplication which we can remove once we have implemented the pprof exporter.
Changes to `FindClosestActivation` were due to the compiler complaining(see https://github.com/signalfx/splunk-otel-js/pull/502/commits/4933e40f20d14985e645cc69f846820ccbe16d50) probably because the second occurrence made it so it wasn't inlined anymore. The previous implementation was arguably somewhat more elegant, but the current one removes any confusion for the compiler and the unused `endTime`. If there's a better way to approach this, let me know.

feat: implement a way to collect unformatted stacktrace lines from profiler

---

docs/advanced-config.md
src/profiling/OTLPProfilingExporter.ts
src/profiling/index.ts
test/profiling/exporter.test.ts
test/profiling/profiling.test.ts

Previously we only allowed endpoints without a scheme, but according to the OTel spec, `http` and `https` schemes must be handled.
Allowed values now:
* `host:port` - insecure gRPC credentials
* `http://host:port` - insecure gRPC credentials
* `https://host:port` - secure gRPC credentials,  certs are loaded according to OTLP cert env vars

fix: handle endpoint scheme for profiling exporter

---

src/native_ext/profiling.cpp
src/profiling/index.ts
test/profiling/extension.test.ts
test/profiling/profiling.test.ts
test/utils.ts

Adding tests for the tracing in JS side.
While doing that noticed, that double-stoping or stopping and then collecting resulted in a runtime crash. added a fix for that as well.
Another unexpected behavior was about starting the profiler. Currently done in `setImmediate` which means that syncronous tasks in the same eventloop round would not be caught by the profiler. Syncronous profiling will thus not work. **Are we OK with that?**
As the bare minimum, we should at least return a promise so it would be possible to await for the profiler to start before doing any work. OR opt in for syncronous start and make users wrap it on their own if they want to leave their startup times unaffected.

fix: avoid crashes with profiler double-stops + test tracing info

---

src/tracing/options.ts

This is a temporary workaround for https://github.com/open-telemetry/opentelemetry-js/issues/3094

fix: set BSP interval to 500ms

---

change/@splunk-otel-fe8fde88-7d17-48e4-9a86-0052e39bf3aa.json
src/profiling/index.ts
test/profiling/profiling.test.ts

Made starting profiler sync and removed a test that relies on the async behavior.

feat: start profiler syncronously

---

.github/workflows/ci.yml
src/native_ext/profiling.cpp
src/profiling/index.ts

`sample` - a call stack sample taken by the profiler at given intervals
**Problem**
Due to the V8 profiler start/stop workaround, we launch a new profiling run before finishing the previous run. When the new run starts, a sample is taken right away (after indeterminate amount of microseconds), which always creates a sample when collecting profiling data and toggling the V8 profiler (i.e. every 30 seconds), this means 1 sample (using sample interval of 1s) out of 30 is always the profiler's collect step. This causes a nasty bias in the data, where it looks like our profiler's collect step is taking way more time than it actually does.
For example during a collection interval of 30 seconds, 1/30 of the samples is the collect step, 2/30 samples are application code and 27/30 is idle. When …

fix: profiling: avoid biased samples due to self sampling

---

CHANGELOG.json
CHANGELOG.md
change/@splunk-otel-2d6ee85d-fc60-475e-803d-c860c932e1f4.json
change/@splunk-otel-49465f6c-6085-48b7-ba27-5e6ced09f9a4.json
examples/basic/package.json
examples/express/package.json
examples/log-injection/package.json
examples/logs/package.json
examples/mixed/package.json
examples/profiling/package.json
package-lock.json
package.json
src/version.ts

https://github.com/signalfx/splunk-otel-js/pull/523
https://github.com/signalfx/splunk-otel-js/pull/530

chore: release v1.3.0

---

scripts/prebuild-os.js
src/profiling/index.ts
src/start.ts
src/tracing/index.ts
test/profiling/extension.test.ts
test/profiling/profiling.test.ts

Profiling tests: on a few platforms (Windows, macOS) not enough stacktraces were received in a given interval. Increased the spin loop duration.
`stop` should have been awaited on, but awaiting on stop threw an error because it seems shutting down an OTel tracer provider will throw when it is exporting on shutdown. The default exporter was OTLP gRPC, which was unable to send the traces so it threw an error.
I added a catch to the tracer provider shutdown that instead logs the error as there are other signals needing to be stopped after tracing. Not catching would cause other signals to not be stopped.
Additionally removed unsupported Node.js versions from the prebuild:os script.

fix: reduce test flakiness

---

binding.gyp
src/native_ext/ext.h
src/native_ext/metrics.h
src/native_ext/module.cpp
src/native_ext/profiling.h
src/native_ext/splunk_v8.h

Older GCC versions don't support `-Wno-cast-function-type` which is needed to include either `v8` or `nan` due to these causing warnings (which we take as errors). Resolved it with pragmas and a compiler version check.
`-Wno-attributes` is used to get rid of unknown (to GCC 4.x) deprecation attributes, e.g. `[[deprecated]]`.
Fixes https://github.com/signalfx/splunk-otel-js/issues/546

fix: add compilation support for older (<8) GCC versions

---

.eslintrc.js
.prettierrc.json
src/instrumentations/http.ts
src/instrumentations/index.ts
src/instrumentations/redis.ts
src/profiling/DebugExporter.ts
src/profiling/OTLPProfilingExporter.ts
src/resource.ts
src/start.ts
src/tracing/index.ts
src/utils.ts
test/instrumentation/redis.test.ts
test/instrumentations.test.ts
test/loginjection.test.ts
test/metrics.test.ts
test/options.test.ts
test/profiling/profiling.test.ts
test/propagation.test.ts
test/servertiming.test.ts
test/uri_parameter_capture.test.ts
test/utils.ts

Current formatting rules deny parentheses around arrow function arguments, which means that the formating is different for functions that have 1 argument compared to when it has 0 or 2+. That has been annoying for me during dev. Please consider changing the lint rule.
Seems like it should be [prettier default](https://prettier.io/docs/en/options.html#arrow-function-parentheses), but for some reason(`gts`?) didn't apply to us.

style: require parentheses around arrow function arguments

---

.github/workflows/check-links.yml
.github/workflows/ci.yml
.github/workflows/lint.yml

Added CentOS 7 compilation and tests.
Additionally:
* The CI was taking a bit too long, so parallelized all the possible workflows.
* Upgraded GitHub Actions tooling
* Move lint and link checks to PR only
* Remove duplicate checks by running the same CI both on pushes and PRs
https://www.youtube.com/watch?v=AbSehcT19u0

chore: add Centos 7 to CI checks, parallelize CI

---

src/profiling/index.ts
src/tracing/index.ts

Previously when profiling and tracing were started, OTel logged a diagnostic error due to an attempt to overwrite the context manager global (which is not possible) in `startTracing`. Disabled setting up tracing's context manager once profiling has been set up.
Additionally when tracing is started there's now a more helpful error message. Note that this case will be impossible with `start` API (which isn't yet properly documented).
Fixes https://github.com/signalfx/splunk-otel-js/issues/534

fix: don't produce error messages when tracing is started before profiling

---

CHANGELOG.json
CHANGELOG.md
examples/basic/package.json
examples/express/package.json
examples/log-injection/package.json
examples/logs/package.json
examples/mixed/package.json
examples/profiling/package.json
package-lock.json
package.json
src/version.ts

- chore: upgrade to signalfx 7.5.0 for Node.js 18 support [#557](https://github.com/signalfx/splunk-otel-js/pull/557)
- fix: don't log a diagnostic error when profiling is started [#556](https://github.com/signalfx/splunk-otel-js/pull/556)

chore: release v1.4.1

---

.github/workflows/ci.yml
README.md
change/@splunk-otel-ea2500da-2998-4119-be1d-6ea0586cff7e.json
docs/advanced-config.md
package-lock.json
package.json
src/tracing/options.ts
test/options.test.ts

Continuation of https://github.com/signalfx/splunk-otel-js/pull/560
Additional changes:
* Use a version of `@opentelemetry/exporter-trace-otlp-proto` that is compatible with Node.js 12.x

feat(v1): deprecate Jaeger exporter

---

docs/advanced-config.md
src/start.ts

`instrumentations` should only be part of `tracing` configuration.

fix: remove instrumentations from common config

---

src/metrics/index.ts
src/profiling/index.ts
src/profiling/types.ts
src/start.ts
src/tracing/index.ts
test/start.test.ts

When signal-specific options were given for `start`, the types required all of the fields to be set, but `start{Tracing,Metrics,Profiling}` were using `Partial<Options>` types.

fix: allow partial signal options being passed to start

---

docs/advanced-config.md
docs/metrics.md
src/instrument.ts
src/metrics/index.ts
src/start.ts
test/metrics.test.ts
test/start.test.ts

* Enable runtime metrics by default if metrics are enabled
* Enable metrics if memory profiling is enabled

feat: enable runtime metrics by default and for memory profiling

---

scripts/release-message.js

Going to get rid of beachball / CHANGELOG.json after this, can't write detailed changelogs with it anyway.

chore: remove usage of changelog.json from releaser script

---

src/metrics/index.ts

OTLP exporters already have their own checks for environment variables, if none exist they set it to the default (localhost:4317 or localhost:4318, depending on the exporter).

fix: don't use default endpoint for metrics

---

docs/advanced-config.md
examples/basic/README.md
examples/express/.env.otlp-splunk
examples/mixed/README.md
src/tracing/options.ts
src/utils.ts
test/instrumentation/redis.test.ts
test/options.test.ts
test/propagation.test.ts
test/tracing/tracing.test.ts
test/uri_parameter_capture.test.ts

* Drop dubious possible values for `OTEL_TRACES_EXPORTER`, e.g. `otlp-splunk` which meant the HTTP protobuf exporter.
* Switching between gRPC and HTTP is now done via `OTEL_EXPORTER_OTLP_PROTOCOL` and `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL` with the latter taking precedence as per OTel spec.
* Add support for `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`. Order of precedence: programmatically -> `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` -> `OTEL_EXPORTER_OTLP_ENDPOINT`.
* It is now possible to specify multiple exporters, separated by commas to `OTEL_TRACES_EXPORTER`. The only accepted values for now are `otlp` and `console`.

feat: add support for OTEL_EXPORTER_OTLP_PROTOCOL, OTEL_EXPORTER_OTLP_ENDPOINT

---

.github/workflows/ci.yml
.github/workflows/e2e-test-released-package.yml

Instead of running e2e tests on published packages for each push and PR, run them:
* Daily at 0600 UTC
* On new published releases (when a release is made, the package is already in npm)

test: run e2e for published packages daily and on new releases

---

docs/troubleshooting.md
src/start.ts
src/types.ts
src/utils.ts
test/start.test.ts
test/utils.test.ts

* New optional option to `start`: `logLevel`. Setting it configures the OTel diagnostic console logger with the specified log level.
* Can also be set via `OTEL_LOG_LEVEL`. Previously this only set the log level but did not create the logging pipeline.
Fixes:
* https://github.com/signalfx/splunk-otel-js/issues/293
* https://github.com/signalfx/splunk-otel-js/issues/598

feat: better diagnostic logging configuration

---

src/detectors/ProcessDetector.ts
test/options.test.ts
test/resource.test.ts

* Command line values are removed from resource detector due to ingest limitations.
* Removed runtime description as it provides no information about Node.js and is not [required by the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/process.md#javascript-runtimes)

feat: remove command line values from process detector

---

src/instrument.ts

The instrument script was missing handling of `OTEL_LOG_LEVEL`

fix: enable log pipeline for instrument script

---

src/metrics/index.ts
test/metrics.options.test.ts

The endpoint is overwritten in the OTLP exporter factory anyway

fix: don't create metrics endpoint too early

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

For a list of major changes and features in `2.0.0` see the notes for [`2.0.0-rc1`](https://github.com/signalfx/splunk-otel-js/blob/main/CHANGELOG.md#200-rc1).
Additional changes in this release:
- Upgrade to OpenTelemetry JS 1.8.0 / 0.34.0. [#612](https://github.com/signalfx/splunk-otel-js/pull/612)
- Remove `@opentelemetry/instrumentation-aws-lambda` from the bundled packages as there exists a separate [lambda instrumentation](https://github.com/signalfx/splunk-otel-lambda) and due to the package not being compatible with `@opentelemetry/instrumentation@0.34.0`. [#612](https://github.com/signalfx/splunk-otel-js/pull/612).
- `@opentelemetry/api` is now a peer dependency and the required version has been bumped to `1.3.0`.
- `OTEL_LOG_LEVEL` now also sets up the logging pipeline, thus …

chore: release v2.0.0

---

src/metrics/index.ts
src/profiling/index.ts
src/tracing/options.ts
src/utils.ts
test/metrics.test.ts
test/options.test.ts
test/profiling/profiling.test.ts
test/service_name.test.ts

Unless explicit service name is set, instead of defaulting to `unnamed-node-service`, an attempt will be made to read the package name from current working directory's package.json. If this can't be done or does not exist, only then is `unnamed-node-service` used.

feat: read service name from package.json

---

src/instrument.ts
test/instrument.test.ts

Adds a new environment variable `SPLUNK_AUTOINSTRUMENT_PACKAGE_NAMES` which can be used to specify an allowlist of package names. When set, only the packages matching the list will be autoinstrumented.

feat: autoinstrument: add early exit based on application name

---

test/examples/utils.js
test/profiling/extension.test.ts

Due to timestamp precision loss in OTLP's exporter, the spans in integration tests might have identical timestamps. This causes flaky tests.
Until https://github.com/open-telemetry/opentelemetry-js/issues/2643 gets fixed, changed the comparison to be trace shape based, i.e. parent-child relationships are checked for inside a trace.

test: don't compare spans by timestamps in integration tests

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

From the CHANGELOG:
- Fixed `SPLUNK_REALM` environment variable taking precedence over endpoint supplied programmatically. `endpoint` now correctly overrides the endpoint created via `SPLUNK_REALM` and when both are set logs a warning. [#668](https://github.com/signalfx/splunk-otel-js/pull/668)
- Empty environment variables are now considered as not defined. [#693](https://github.com/signalfx/splunk-otel-js/pull/693)
- New configuration option: `SPLUNK_DEBUG_METRICS_ENABLED` / `metrics.debugMetricsEnabled`. [#700](https://github.com/signalfx/splunk-otel-js/pull/700) When set, extra set of internal troubleshooting metrics are produced. This should only be enabled to assist debugging. Defaults to `false`. Currently debug metrics for the CPU and memory profiler are produced, each being a …

chore: release v2.2.0

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Fixed [`@opentelemetry/instrumentation-mongoose`](https://www.npmjs.com/package/@opentelemetry/instrumentation-mongoose) not being loaded. [#715](https://github.com/signalfx/splunk-otel-js/pull/715)

chore: release v2.2.1

---

src/start.ts
src/utils.ts
test/start.test.ts

Attributes meant for `start` were passed to signals. It broke when `startTracing` saw `logLevel` passed to it from `start` and errored due to the  `assertNoExtraneousProperties` check.
Solution: filter out the attributes from common config that the signals can handle.

fix: don't pass all shared options to signals

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Fixed `logLevel` configuration option for `start` function throwing an error [#741](https://github.com/signalfx/splunk-otel-js/pull/741)
- Added Docker image for the OpenTelemetry Operator for Kubernetes [#740](https://github.com/signalfx/splunk-otel-js/pull/740)

chore: release v2.2.3

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- fix: pin OpenTelemetry dependencies to avoid multiple versions of `@opentelemetry/instrumentation` packages being loaded at the same time [#745](https://github.com/signalfx/splunk-otel-js/pull/745)

chore: release v2.2.4

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Upgrade to OpenTelemetry `1.15.1` / `0.41.1`. [#761](https://github.com/signalfx/splunk-otel-js/pull/761)
- Fix confusing error message regarding `grpc`: `@opentelemetry/instrumentation-grpc Module @grpc/grpc-js has been loaded before @opentelemetry/instrumentation-grpc so it might not work, please initialize it before requiring @grpc/grpc-js`. `grpc` is internally now lazily loaded. [#762](https://github.com/signalfx/splunk-otel-js/pull/762)
- Allow enabling and disabling instrumentations via environment variables by introducing `OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED` and `OTEL_INSTRUMENTATION_[NAME]_ENABLED`. [#769](https://github.com/signalfx/splunk-otel-js/pull/769)

chore: release v2.3.0

---

.github/workflows/ci.yml
binding.gyp
scripts/prebuild-os.js

And add Node 20 to testing matrix.

feat: support native builds with Node 20

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Upgrade to OpenTelemetry `1.15.2` / `0.41.2`. [#778](https://github.com/signalfx/splunk-otel-js/pull/778)

chore: release v2.3.2

---

README.md
src/tracing/index.ts

Constructing `NodeTracerProvider` with `OTEL_TRACES_EXPORTER` set logs an error, e.g. `Exporter "otlp" requested through environment variable is unavailable.` Nothing actually goes wrong, but the error message is confusing for users.
Workaround for https://github.com/open-telemetry/opentelemetry-js/issues/3422

fix: add workaround for OTEL_TRACES_EXPORTER logging an error message

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Fix the error message about an unavailable exporter (e.g. `Exporter "otlp" requested through environment variable is unavailable.`) when `OTEL_TRACES_EXPORTER` is set. Workaround for https://github.com/open-telemetry/opentelemetry-js/issues/3422. [#783](https://github.com/signalfx/splunk-otel-js/pull/783)
- Explicitly set a meter provider for instrumentations. `NoopMeterProvider` is set by default. If metrics are enabled and `SPLUNK_INSTRUMENTATION_METRICS_ENABLED` is set to true, instrumentation specific metrics will be emitted, for example `http.server.duration` from the `http` instrumentation. [#784](https://github.com/signalfx/splunk-otel-js/pull/784)

chore: release v2.4.0

---

src/start.ts

AWS Lambda instrumentation needs a `forceFlush` method to be existing on a meter provider else it logs an error for each span. (https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts#L296)
The thing is even OTel's own `NOOP_METER_PROVIDER` doesn't have it.

fix: missing forceFlush on noop meter provider

---

src/start.ts

MeterProvider's forceFlush returns a promise:
https://github.com/open-telemetry/opentelemetry-js/blob/8ac369f87e792702045f9847c7ab4ac72aa48ce2/packages/sdk-metrics/src/MeterProvider.ts#L114
[AWS Lambda instrumentation uses `Promise.all` on the result of `forceFlush`,](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts#L356) while this works I think it's better to make it 100% compatible in case there are calls to `forceFlush().then()` anywhere

fix: make noopmeterprovider forceFlush return a promise

---

.eslintignore
.github/workflows/ci.yml
.github/workflows/e2e-test-released-package.yml
examples/typescript/.dockerignore
examples/typescript/index.ts
examples/typescript/package.json
examples/typescript/tsconfig.json
test/examples/collector.config.yml
test/examples/typescript.override.yml
test/examples/typescript/app.env
test/examples/typescript/index.js
test/examples/typescript/snapshot.js

Add a small TypeScript example that will also be used in e2e tests - so we know the published package does not have any export breakages.

test: add typescript e2e test

---

src/metrics/index.ts
test/metrics.options.test.ts

The code was throwing when `OTEL_METRICS_EXPORTER=none`, but `none` [is a valid value](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#exporter-selection).

fix: support 'none' value for OTEL_METRICS_EXPORTER

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Add support for `OTEL_METRICS_EXPORTER=none`. [#801](https://github.com/signalfx/splunk-otel-js/pull/801)

chore: release v2.4.2

---

src/instrumentations/external/kafkajs/kafkajs.ts
src/instrumentations/external/kafkajs/propagator.ts

OTel JS defines carrier keys as lowercase. b3 propagator attempts to read lowercase keys, but other SDKs (Java) produce headers with mixed case keys, causing split traces - https://github.com/open-telemetry/opentelemetry-js/issues/3150
This works fine in the case of HTTP, where node's http module lowercases all keys, but kafkajs retains the key casing.

fix: compare kafka header keys case insensitively

---

.lycheeignore
CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Compare kafka header values case insensitively. Fixed split traces when b3 propagation is used over kafka headers and the producer does not use lowercase keys. [#804](https://github.com/signalfx/splunk-otel-js/pull/804)

chore: release v2.4.3

---

.github/workflows/ci.yml
binding.gyp
src/native_ext/memory_profiling.cpp
src/native_ext/metrics.cpp
src/native_ext/tinystl/allocator.h
src/native_ext/tinystl/buffer.h
src/native_ext/tinystl/new.h
src/native_ext/tinystl/stddef.h
src/native_ext/tinystl/traits.h
src/native_ext/tinystl/vector.h
src/native_ext/util/platform.cpp

Prebuilds now work with CentOS 7 (and any other OS with ancient glibc++), getting rid of the need to install g++ and Python for the compile step.
* Get rid of C++ standard library in the native extension.
- Replace `std::chrono::system_clock` with OS builtins.
- Replace `std::vector` with `tinystl::vector`
- Use `const char*` instead of `std::string` (really small strings) 
* Add CentOS 7 build and prebuilds check to CI.

fix: native extension: support older C++ ABIs

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Support older libc++ ABIs. This should remove the need for a compilation step on CentOS 7 when running npm install. [#806](https://github.com/signalfx/splunk-otel-js/pull/806)

chore: release v2.4.4

---

.github/workflows/test-docker-image.yml
Dockerfile

Since the Docker image `node` doesn't support ppc64le, we need to define the build image using a variance on the builtin argument `TARGETARCH` to build the right image. I also added some tests so changes to the Dockerfile can be tested.

Add more code towards supporting ppc64le

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Prebuild the native module for Node.js 21. [#838](https://github.com/signalfx/splunk-otel-js/pull/838)

chore: release v2.5.1

---

.github/workflows/ci.yml

Add support for ARM64 Linux prebuilds

Linux ARM64 prebuilds

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Add missing telemetry.sdk.version to profiling payloads. #[854](https://github.com/signalfx/splunk-otel-js/pull/854)
- Upgrade to OpenTelemetry `1.18.1` / `0.45.1`. [#852](https://github.com/signalfx/splunk-otel-js/pull/852)
- Add Linux ARM64 prebuilt binaries. [#850](https://github.com/signalfx/splunk-otel-js/pull/850)

chore: release v2.6.0

---

src/native_ext/profiling.cpp

v8 internally caches profiling titles, by using a new profiling title every time the previous titles are kept in memory, leaking around 16 bytes each 30 seconds.

fix: small v8 memory leak, reuse profiling titles

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Fix potential memory leak when CPU profiling is active. [#858](https://github.com/signalfx/splunk-otel-js/pull/858)
- Upgrade to protobuf.js 7.2.5. [#859](https://github.com/signalfx/splunk-otel-js/pull/859)

chore: release v2.6.1

---

.github/workflows/ci.yml
docs/advanced-config.md
scripts/generate-metadata-yaml.js
src/index.ts
src/utils.ts

If possible the instrumentation target library versions are taken from dependency READMEs (however in the future a better mechanism is needed to gather these automatically, something to discuss in the JS sig).
Example yaml can be seen at https://github.com/signalfx/splunk-otel-js/actions/runs/7474145786/artifacts/1159275535

add metadata yaml generation

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Upgrade to OpenTelemetry `1.21.0` / `0.48.0`. [#874](https://github.com/signalfx/splunk-otel-js/pull/874)
- GraphQL instrumentation: spans for resolvers are no longer generated. This brings in significant performance improvements for queries hitting lots of resolvers. `SPLUNK_GRAPHQL_RESOLVE_SPANS_ENABLED=true` environment variable can be used to unignore resolve spans.

chore: release v2.7.0

---

src/profiling/OTLPProfilingExporter.ts
test/profiling/exporter.test.ts

`profiling.data.total.frame.count` should be the amount of total frames, not stacktraces.

fix: reported profiling stack frame count

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Upgrade to OpenTelemetry `1.25.1` / `0.52.1`. [#912](https://github.com/signalfx/splunk-otel-js/pull/912)
- Use kafkajs instrumentation from upstream. [#913](https://github.com/signalfx/splunk-otel-js/pull/913)

chore: release v2.9.0

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Use environment, process, host and OS detectors from upstream. Update container detector to support cgroup v2. [#925](https://github.com/signalfx/splunk-otel-js/pull/925)
- Use explicit imports when loading instrumentations [#926](https://github.com/signalfx/splunk-otel-js/pull/926)

chore: release v2.10.0

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Bundle instrumentations for `undici`, `socket.io` and `lru-memoizer` by default. [#934](https://github.com/signalfx/splunk-otel-js/pull/934)

chore: release v2.11.0

---

src/index.ts

So that user gets editor hints about deprecation (dash-through, comments)

refactor: add @deprecated annotation to deprecated functions

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Add `resourceFactory` option for traces. Allows for customization of the detected resource. Previously a resource could be provided via `tracerConfig`, but this overwrote the detected attributes. For backwards compatibility the latter option is still possible. [#938](https://github.com/signalfx/splunk-otel-js/pull/938)
- Support `none` value for `OTEL_TRACES_EXPORTER` and `OTEL_METRICS_EXPORTER` environment variables. [#939](https://github.com/signalfx/splunk-otel-js/pull/939)
- Use the default `OTEL_BSP_SCHEDULE_DELAY` of `5000` instead of `500`. This was a workaround for an old `BatchSpanProcessor` bug where it failed to flush spans fully. [#940](https://github.com/signalfx/splunk-otel-js/pull/940)
- Disable log sending for Winston instrumentation by default. Add `winston-transport` …

chore: release v2.12.0

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Add an optional workaround for Next.js span cardinality issues. Can be enabled by setting `SPLUNK_NEXTJS_FIX_ENABLED` to `true`. [#957](https://github.com/signalfx/splunk-otel-js/pull/957)

chore: release v2.13.0

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Add Node.js 22 to prebuilds. [#963](https://github.com/signalfx/splunk-otel-js/pull/963)

chore: release v2.14.0

---

.github/workflows/e2e-test-released-package.yml

The tests on the main branch have been changed and aren't compatible with the released 2.x packages

Run released package e2e tests from 2.x branch

---

src/instrument.ts
src/instrumentations/http.ts
src/instrumentations/index.ts
src/logging/index.ts
src/logging/types.ts
src/metrics/index.ts
src/metrics/types.ts
src/profiling/index.ts
src/profiling/types.ts
src/resource.ts
src/start.ts
src/tracing/index.ts
src/tracing/options.ts
src/tracing/types.ts
src/utils.ts
test/common_options.test.ts
test/metrics.options.test.ts
test/options.test.ts
test/start.test.ts
test/utils.ts

* `instrument` script now uses the `start` call instead of duplicating the logic.
* New option for `start`:`resource` - a method which is called with the detected environment resource. Users can return their own resource from this function, which gets passed to all signals (instead of doing it separately for all signals - where the API for it differed).
* New option for `start`: `realm` - when specified the `realm` is passed to the underlying signals. Only applicable for traces and metrics at the moment as logs and profiling data can't be sent directly over OTLP.
* Resource detection is now cached. Previously each signal called the same detection routines.
* When `http/protobuf` (the default setting) is enabled and `endpoint` option is set, signals now attach the resource path to the …

start API improvements

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Upgrade to OpenTelemetry `1.28.0` / `0.55.0`. [#987](https://github.com/signalfx/splunk-otel-js/pull/987)

chore: release v2.15.0

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

Will test out the release pipeline.
3.0.0 changes:
- Raise the minimum required Node.js version to 18. If Node <18 is a requirement, [2.x](https://github.com/signalfx/splunk-otel-js/tree/2.x) is still maintained and package versions 2.x can be used..
- Change the default OTLP protocol from `grpc` to `http/protobuf`. The default exporting endpoint has been changed from `http://localhost:4317` to `http://localhost:4318`. Signal specific URL paths are automatically added when choosing the endpoint, e.g. when `endpoint` is set to `http://collector:4318`, `/v1/traces` is added for traces.
- Change the default sampler from `parentbased_always_on` to `always_on`.
- Improve the start API to avoid duplicating parameters in the signal specific configuration.
* Add `resource` field - a function …

chore: release v3.0.0-rc1

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Raise the minimum required Node.js version to 18. If Node <18 is a requirement, [2.x](https://github.com/signalfx/splunk-otel-js/tree/2.x) is still maintained and package versions 2.x can be used..
- Change the default OTLP protocol from `grpc` to `http/protobuf`. The default exporting endpoint has been changed from `http://localhost:4317` to `http://localhost:4318`. Signal specific URL paths are automatically added when choosing the endpoint, e.g. when `endpoint` is set to `http://collector:4318`, `/v1/traces` is added for traces.
- Change the default sampler from `parentbased_always_on` to `always_on`.
- Improve the start API to avoid duplicating parameters in the signal specific configuration.
* Add `resource` field - a function which can be used to overwrite or add additional …

chore: release v3.0.0

---

.eslintrc.js
.github/workflows/ci.yml
NOTICE
package-lock.json
package.json
src/instrumentations/external/neo4j/index.ts
src/instrumentations/external/neo4j/neo4j.ts
src/instrumentations/external/neo4j/semconv.ts
src/instrumentations/external/neo4j/types.ts
src/instrumentations/external/neo4j/utils.ts
test/instrumentation/external/neo4j/neo4j.test.ts
test/instrumentation/external/neo4j/utils.ts
test/runner.js
test/utils.ts

Ported over Aspecto's [neo4j instrumentation](https://github.com/aspecto-io/opentelemetry-ext-js/tree/master/packages/instrumentation-neo4j).
Changes:
* Support version 5.x
* Added additional typing
* Moved tests to `node:test`
* Converted deprecated attributes to local `ATTR_` keys.
* Fixed the case where spans were being ended twice

Add neo4j driver instrumentation

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Add prebuilds for Apple silicon. [#1016](https://github.com/signalfx/splunk-otel-js/pull/1016)
- Fix compilation on macOS with Xcode 16.3. [#1016](https://github.com/signalfx/splunk-otel-js/pull/1016)

chore: release v3.1.2

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Upgrade to OpenTelemetry SDK 2.0. [#1020](https://github.com/signalfx/splunk-otel-js/pull/1020)
- Add an experimental HTTP instrumentation based on diagnostics channel. [#1021](https://github.com/signalfx/splunk-otel-js/pull/1021)

chore: release v4.0.0-alpha1

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Upgrade to OpenTelemetry `1.30.1` / `0.57.2`. [#1024](https://github.com/signalfx/splunk-otel-js/pull/1024)
- Add prebuilt binaries for Node.js 24. [#1024](https://github.com/signalfx/splunk-otel-js/pull/1024)
- Add support for snapshot profiling (callgraphs). [#1023](https://github.com/signalfx/splunk-otel-js/pull/1023)

chore: release v3.2.0

---

scripts/prepare-release-artifact.js

The max number of artifacts from `listWorkflowRunArtifacts` now exceeds the limit of 100, so some of them will be missing in the results. octokit provides a way to filter them at the source

fix: pass the searched artifact name to octokit

---

CHANGELOG.md
package-lock.json
package.json
src/version.ts

- Upgrade to OpenTelemetry SDK 2.0. [#1020](https://github.com/signalfx/splunk-otel-js/pull/1020).
* Minimum Node.js version has been bumped to `^18.19.0 || >=20.6.0`.
* Refer to https://github.com/open-telemetry/opentelemetry-js/releases/tag/v2.0.0 and the [upgrade guide](https://github.com/open-telemetry/opentelemetry-js/blob/main/doc/upgrade-to-2.x.md) for the complete list of breaking changes in OpenTelemetry JS.
* Notable changes relevant to `@splunk/otel`:
* Resource can no longer be created with `new Resource({})`, instead use `resourceFromAttributes({})` when passing in a resource:
```ts
import { start } from '@splunk/otel';
import { resourceFromAttributes } from '@opentelemetry/resources';
start({
resource: (detectedResource) => {
return …
```

chore: release v4.0.0

---

.github/workflows/ci.yml
src/tracing/snapshots/Snapshots.ts

Intended to get more relevant data out of the callgraphs.

reduce default snapshot/callgraph profiler callstack interval to 1ms
