signalfx/splunk-otel-js

- README.md
> Updated readme to list config options in configuration table

- CHANGELOG.md
- package.json
- src/version.ts
Preparing to release v0.5.0
Depends on #46 so that should be merged first.
> Release version 0.5.0

- CHANGELOG.md
- README.md
- package.json
- src/instrumentations/index.ts
- test/instrumentations.test.ts
Add instrumentations from non-contrib sources
> feat: add external instrumentations - elasticsearch, amqplib

- .circleci/config.yml
This restricts secrets only to jobs that need it.
> Use circleci contexts for secrets

- .github/pull_request_template.md
- CHANGELOG.json
- CHANGELOG.md
- RELEASING.md
- change/@splunk-otel-001c4603-3bb6-4d6f-8e53-fb10e4f5e929.json
- change/@splunk-otel-5756ef5a-6dc7-43e9-be09-e4766af9fcf1.json
- change/@splunk-otel-d7339ba6-6f53-4a96-95b4-9412de9b319e.json
- examples/express/package.json
- examples/logs/package.json
- package-lock.json
- package.json
- src/version.ts
- Added change management using beachball (jakubmal+github@gmail.com)
_Replace this with a description of the PR. Explain the problem it solves and the proposed solution._
_List Github/JIRA issue(s) this PR fixes._
Release.
> chore: Release v0.12.0

- examples/basic/README.md
- examples/basic/index.js
- test/examples/basic/snapshot.js
- test/examples/utils.js
Some small changes to make the basic example consistent with the others + actually properly assert attributes on spans.
> fix: fix inconsistencies in the basic example

- .gitignore
- examples/basic/.gitignore
- examples/basic/package.json
- examples/express/.gitignore
- examples/express/package.json
- examples/logs/.gitignore
- examples/mixed/.gitignore
- examples/mixed/package.json
Few small cleanups I stumbled upon.
> chore: remove unneeded gitignore files

- CHANGELOG.json
- CHANGELOG.md
- change/@splunk-otel-617b13c9-328a-4e4b-bd44-42a157069ae0.json
- change/@splunk-otel-86417fa2-cdee-40b1-ae07-23160896581b.json
- change/@splunk-otel-8acd8087-05ea-418e-9fa8-cd0cf4298f73.json
- change/@splunk-otel-ba9ac324-9f97-419b-890e-aa3e6b8bd70a.json
- change/@splunk-otel-ef2a74d6-56a4-4cf5-8df1-ac53a5b462b0.json
- package.json
- src/version.ts
> chore: release v0.13.0

- .gitlab-ci.yml
- dist/checksums.txt
Release Job in the internal repo is failing.
> chore: fix the release pipeline

- .github/workflows/ci.yml
- examples/basic/package.json
- examples/express/package.json
- examples/log-injection/package.json
- examples/logs/package.json
- examples/mixed/package.json
Also fixes our e2e tests on published versions.
> chore: update examples

- docs/http-instrumentation.md
> doc: add missing words to http instrumentation docs

- package-lock.json
- package.json
> chore: remove @types/sonic-boom from dependencies

- CHANGELOG.json
- CHANGELOG.md
- change/@splunk-otel-4e785909-3e8b-487b-a773-0448e5f0f1a7.json
- change/@splunk-otel-710fb8ca-8079-4201-89c3-45337bc8ce67.json
- package-lock.json
- package.json
- src/version.ts
> chore: release v0.15.0

- .github/workflows/ci.yml
- change/@splunk-otel-eeb68c70-397f-4f96-bf05-17cb1721ce8a.json
- docs/advanced-config.md
- package-lock.json
- package.json
- src/instrumentations/redis.ts
- src/tracing.ts
- test/instrumentation/redis.test.ts
- test/instrumentations.test.ts
Same as https://github.com/signalfx/splunk-otel-js/pull/420
CI was stuck on a non-existent job
> feat: add env var to incorporate redis command's arguments

- README.md
> chore: add GDI badge

- test/examples/collector.config.yml
- test/examples/e2e.docker-compose.yml
- test/examples/utils.js
Migrate from polling to httpsink exporter.
> Migrate from polling exporter to httpsink exporter

- src/metrics/index.ts
- src/options.ts
- src/profiling/index.ts
- src/resource.ts
- test/instrumentations.test.ts
- test/resource.test.ts
No significant updates. Updated the env detector from upstream to make the next PR(adding process detector) smaller.
> refactor: update env detector from upstream

- scripts/prepare-release-artifact.js
Should find the correct workflow type now.
> fix: releaser: only look for ci workflow runs

- change/@splunk-otel-42417487-cc55-467d-b741-9e94bb35bb9e.json
- docs/advanced-config.md
- src/options.ts
We often let our people or the customer debug the pipeline. It would be convenient to enable them to cut out possible issues with exporter during debugging.
> feat: implement setting up ConsoleSpanExporter via env var

- .github/workflows/ci.yml
- binding.gyp
- change/@splunk-otel-720ca615-45a6-44a5-832e-ac1622535e24.json
- package-lock.json
- package.json
- scripts/prebuild-os.js
> feat: add builds for node 18

- README.md
- change/@splunk-otel-835859df-2920-4280-93ed-07aba289641d.json
- package.json
- src/instrumentations/index.ts
- test/instrumentations.test.ts
Just like redis instrumentation, this is now moved to opentelemetry's repo.
> chore: remove support for `opentelemetry-instrumentation-amqplib`

- CHANGELOG.json
- CHANGELOG.md
- change/@splunk-otel-0d06dbe4-c2ce-4e84-a4b8-8ff2a2ce1b77.json
- examples/basic/package.json
- examples/express/package.json
- examples/log-injection/package.json
- examples/logs/package.json
- examples/mixed/package.json
- package.json
- src/version.ts
Only user-facing change is adding shutdown to stop and exposing `stopTracing`.
> chore: release v1.1.0

- CHANGELOG.json
- CHANGELOG.md
- change/@splunk-otel-345cf72a-5e0b-4e99-9034-dd82ede484b4.json
- examples/basic/package.json
- examples/express/package.json
- examples/log-injection/package.json
- examples/logs/package.json
- examples/mixed/package.json
- package-lock.json
- package.json
- src/version.ts
Diff: https://github.com/signalfx/splunk-otel-js/compare/4d954d0bc9939228e800bf840c18cc100abbfcf4..5bb8cc9fc91f6e92008aa079eae85b02f786c440
> chore: release v1.2.0

- .github/workflows/ci.yml
- examples/profiling/.dockerignore
- examples/profiling/README.md
- examples/profiling/collector-config.yml
- examples/profiling/docker-compose.yml
- examples/profiling/index.js
- examples/profiling/package.json
- scripts/examples-npm-install
- src/profiling/OTLPProfilingExporter.ts
- src/profiling/index.ts
- test/examples/Dockerfile_app
- test/examples/profiling.override.yml
- test/examples/profiling/app.env
- test/examples/profiling/index.js
- test/examples/profiling/snapshot.js
Profiling had nothing to smoke test the final packaged version. Building #507 I noticed that I could've shipped a version that breaks prod without catching this in tests.
> test: e2e test enabling profiling

- CHANGELOG.json
- CHANGELOG.md
- change/@splunk-otel-fe8fde88-7d17-48e4-9a86-0052e39bf3aa.json
- examples/basic/package.json
- examples/express/package.json
- examples/log-injection/package.json
- examples/logs/package.json
- examples/mixed/package.json
- examples/profiling/package.json
- package-lock.json
- package.json
- src/version.ts
* https://github.com/signalfx/splunk-otel-js/pull/518
* https://github.com/signalfx/splunk-otel-js/pull/519
> chore: release v1.2.1

- src/profiling/DebugExporter.ts
- src/profiling/OTLPProfilingExporter.ts
- test/options.test.ts
Lint started failing after merging in 2 PRs after https://github.com/signalfx/splunk-otel-js/pull/548
> refactor: use parentheses around closure args

- CHANGELOG.json
- CHANGELOG.md
- change/@splunk-otel-04620656-d9ff-4f33-b1c8-57d9680e41bb.json
- examples/basic/package.json
- examples/express/package.json
- examples/log-injection/package.json
- examples/logs/package.json
- examples/mixed/package.json
- examples/profiling/package.json
- package-lock.json
- package.json
- src/version.ts
- Add detector for container ID (cgroup v1) [#515](https://github.com/signalfx/splunk-otel-js/pull/515)
- Memory profiling [#524](https://github.com/signalfx/splunk-otel-js/pull/524)
- Support compilation on CentOS 7 [#552](https://github.com/signalfx/splunk-otel-js/pull/552)
> chore: release v1.4.0

- package-lock.json
- package.json
Fixes https://github.com/signalfx/splunk-otel-js/issues/504
> chore: upgrade to signalfx 7.5.0

- .gitlab-ci.yml
_Replace this with a description of the PR. Explain the problem it solves and the proposed solution._
_List Github/JIRA issue(s) this PR fixes._
> chore: fossa

- README.md
1. "Project" term is used in an informal way and we can  skip this word here
1. "license (verb)" - grant license to something
1. I think we want to license not only the releases but also other artifacts such as the codebase
> Update License header

- CHANGELOG.md
- package-lock.json
- package.json
- src/version.ts
See the included changelog for a list of changes included in the release.
> chore: release v2.0.0-rc1

- README.md
https://github.com/badges/shields/issues/8671
> chore: fix build badge

- CHANGELOG.md
- package-lock.json
- package.json
- src/version.ts
- Internal: added frame count to profiling data. [#726](https://github.com/signalfx/splunk-otel-js/pull/726)
> chore: release v2.2.2

- .github/workflows/publish-docker-image.yml
- Dockerfile
This will create an image which has the directory `/splunk-otel-js` containing the distro and node_modules.
> feat: add Docker image

- CHANGELOG.md
- package-lock.json
- package.json
- src/version.ts
> chore: release v2.3.1

- .github/workflows/cla.yml
Per https://github.com/signalfx/gdi-specification/pull/269
>  Add CLA Assistant GitHub workflow

- package-lock.json
- package.json
Requested in https://github.com/signalfx/splunk-otel-js/issues/768
Should fix a few CVEs
> chore: upgrade to protobuf.js 7.2.5

- CHANGELOG.md
- package-lock.json
- package.json
- src/version.ts
- Fix reporting of `profiling.data.total.frame.count`. [#886](https://github.com/signalfx/splunk-otel-js/pull/886)
> chore: release v2.7.1

- CHANGELOG.md
Fixed the changelog as it caused the release to fail
> chore: release v2.11.0

- package-lock.json
- package.json
Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2624
> upgrade hapi instrumentation to 0.45.1

- package-lock.json
- package.json
* Get rid of `cross-env` (unused)
* Update `typeorm` due to a security warning
* Update `nan` to latest
> update dev deps

- CHANGELOG.md
- package-lock.json
- package.json
- src/version.ts
- Fix loading of neo4j-driver instrumentation. [#1013](https://github.com/signalfx/splunk-otel-js/pull/1013)
> chore: release v3.1.1

- scripts/generate-metadata-yaml.js
* Updated metadata generation script to first generate an object following the schema, and then output that in yaml format
* Added exported metrics into the output
* Fix neo4j typo in instrumentation name
Note: Still need to mark those metrics as bundled, however it hasn't been determined yet how it should be labeled
Updated output: 
[splunk-otel-js-metadata.yaml.txt](https://github.com/user-attachments/files/19648300/splunk-otel-js-metadata.yaml.txt)
(.txt due to github limitations)
> Update generated metadata, include instrumentation's metrics

- .github/workflows/ci.yml
- src/native_ext/ext.h
- src/native_ext/memory_profiling.h
- src/native_ext/metrics.cpp
https://github.com/signalfx/splunk-otel-js/pull/1016
> 2.x: fix macos compilation with xcode 16.3

- CHANGELOG.md
- package-lock.json
- package.json
- src/version.ts
- Add the option to use AWS Xray propagator. [#1028](https://github.com/signalfx/splunk-otel-js/pull/1028)
> chore: release v3.3.0

- .gitlab-ci.yml
- packages/otel-esbuild-plugin/CHANGELOG.md
- packages/otel-esbuild-plugin/package.json
- scripts/prepare-release-artifact.js
- scripts/release-github.js
- scripts/release-message.js
- Add GitLab CI job for esbuild plugin releases  
- Update release scripts to support workspace packages
- Add initial CHANGELOG.md for esbuild plugin v0.0.1
- Configure release pipeline for `esbuild-plugin-v*` tags
> chore(esbuild-plugin): add release setup for esbuild plugin package
